dist: trusty
sudo: true

language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    # - python: 3.4
    #   env: TOXENV=py34
    # - python: 3.5
    #   env: TOXENV=py35
    # - python: 3.6
    #   env: TOXENV=py36

install: 
  - ./.travis/install.sh tox

script: 
  - ./.travis/run.sh

notifications:
  email: false
