dist: trusty
sudo: true

language: python

#matrix:
 # include:
  #  - python: 2.7
   #   env: TOXENV=py27
    # - python: 3.4
    #   env: TOXENV=py34
    # - python: 3.5
    #   env: TOXENV=py35
    # - python: 3.6
    #   env: TOXENV=py36

env:
  - TOXENV=py27
  #- TOXENV=py34
  #- TOXENV=py35
  #- TOXENV=py36

install: 
  - travis_retry pip install tox;
  - travis_retry pip install check-manifest;
  - travis_retry pip install flake8;

script: 
  - travis_retry tox

notifications:
  email: false
